### ISSUE TITLE
Merge CV into PSI-MS CV

### ISSUE THREAD

**Issue by bittremieux** [HUPO-PSI/mzQC#141]
As per feedback from the PSI internal review, the CV should be merged with the [PSI-MS CV](https://github.com/HUPO-PSI/psi-ms-CV) prior to external review.

**Comment by mwalzer** [comment]
Following up on the call with PSI-MS-Vocab group:
- [ ]  We switch to MS prefix but keep the accession number space.
- [ ]  We attach our root element to the top common PSI-MS CV element
- [ ]  We switch from property_value: to relationship:
- [ ]  We double check for 'duplicates' like retention time, and amend the name with 'column' where applicable or change the name accordingly (I don't think there are any clashes that can't be fixed with ... Column.)
- [ ]  We use PSI-MS has_unit instead of our has_units

**Comment by bittremieux** [comment]
A [PR with the first terms to be merged into the PSI-MS-CV](https://github.com/HUPO-PSI/psi-ms-CV/pull/99) has now been opened. Hoorah! 🎉
