### ISSUE TITLE
Some parent terms not found when loading qc-cv.obo

### ISSUE THREAD

**Issue by biodavidjm** [HUPO-PSI/mzQC#196]
I get the following warning in R when getting the ontology from `qc-cv.obo`

```
ontologyIndex::get_ontology(file = "~/github/hupo-psi/mzQC/cv/qc-cv.obo")

Warning message:
Some parent terms not found: MS:4000003, MS:4000004, MS:4000005 (5 more)
```

**Comment by bittremieux** [comment]
This is because of our current efforts to port the QC CV terms to the PSI-MS-CV, our CV here is indeed in a undefined state with some dangling terms. Do you get similar warnings when loading the [PSI-MS-CV](https://github.com/HUPO-PSI/psi-ms-CV/blob/master/psi-ms.obo)? Are there CV terms that should get priority for porting from the QC CV to PSI-MS-CV for your R development work?

**Comment by bittremieux** [comment]
We have now mostly finished porting our CV terms to the PSI-MS-CV, which should not have these issues.
