### ISSUE TITLE
[CV] Need for new value-types in json

### ISSUE THREAD

**Issue by julianu** [HUPO-PSI/mzQC#62]
Until now, in the CV we have the xref for each term, like "xref: value-type:xsd\:int "The allowed value-type for this CV term."
These value types are still XML specific. 
Do we need to specify them in json, and if, what values types do we have there?

**Comment by bittremieux** [comment]
[JSON has a few different types](https://json-schema.org/understanding-json-schema/reference/type.html):

- string
- Numeric types
- object
- array
- boolean
- null

I've tried to specify the types of the JSON elements in the schema as appropriately as possible. For the parameter values [this hasn't been done though](https://github.com/HUPO-PSI/mzQC/blob/master/schema/v0_0_11/mzqc_0_0_11.schema.json#L103) because they can have any type of value depending on the CV term.
So specifying the type in the CV makes sense as far as I'm concerned. Then we can still validate the types ourselves outside of the JSON schema.

**Comment by julianu** [comment]
I think, this can be closed.
The OBO states the type in more or less the same way as it is required in JSON. We just need to be sure not to set types in the CV, which do not exist in JSON.
