### ISSUE TITLE
[CV] Why is ambient humidity an n-tuple?

### ISSUE THREAD

**Issue by julianu** [HUPO-PSI/mzQC#64]
The term QC:4000068 "Ambient humidity" is currently an n-tuple.
Is there any reason for this? If so, the description (and name) should reflect this.

**Comment by bittremieux** [comment]
It's an n-tuple because first I had this abominable value consisting of a (mean, median, sd, q1, q3, min, max) tuple. I think that by now we all agree that this isn't the way to encode this kind of information, rather each of these values should be an individual term. So this should be changed to a single value.

**Comment by julianu** [comment]
Ok, thanks for the clarification.
