### ISSUE TITLE
Fatal error when trying to use mzQC: namespaces make it impossible to query in standard JSON tools

### ISSUE THREAD

**Issue by Ozzard** [HUPO-PSI/mzQC#99]
Short form: I recommend ditching cv and cvRef completely and moving full URIs into accession; otherwise, mzQC cannot be queried robustly using tooling that walks a JSON tree.

Long form:

I've just finished importing about 8,000 generated mzQC files into the Stoller Biomarker Discovery Centre's live QC database.  It happens to be SQL Server 2014, though the issue I'm going to demonstrate is generic.  Now I'm trying to write queries that will pull out particular metrics.  I'm not sure what tool we'll eventually be using to generate these, so I'm trying to make the query robust, and recognise (say) code 92 (MS1/MS2 ratio) from the ontology at https://raw.githubusercontent.com/HUPO-PSI/mzqc/master/cv/v0_0_11/qc-cv.obo .

My best query at the moment is something along the lines of `$.mzQC.runQuality[0].qualityParameters[?(@.accession = "QC:92")].value`.  Note the hard-coding of the QC: prefix (the hard-coding of the first array element above is a different problem).  Note also the complete irrelevance of the cvRef key; the information in that key is both duplicated and required in accession - I'll open a different issue for that.

As I understand it, the producer of a mzQC file is free to use whatever prefix they wish for the cvRef (aside: why is this duplicated in the accession?) as long as it matches a record in the cv section of the file.  So I cannot rely on a particular cvRef value (or, presumably equivalently, a particular prefix in an accession).  Whatever query tool I use needs to be namespace-aware; and, as JSON has no built-in namespacing, it therefore needs to be aware of mzQC's custom namespace implementation.

Therefore **I cannot use a generic tool to query mzQC in a robust way in the presence of arbitrary prefixes**.

I regard the inability to generate robust queries against a standard format to be a showstopper for our use; I was intending to get mzQC files for the rest of our 50,000 samples, but have now stopped that process until I can find out whether the standard can be changed to be robust.

I can see three options from here:

* Do nothing. Accept that standard query tools cannot be used to query mzQC robustly, and that all querying will have to be done via custom code. This abandons (for example) consumers of mzQC who wish to query via database.
* Standardise the mapping of prefix to URL. This makes versioning unpleasant at best.
* Remove the indirection and include the full URI directly in the accession, as is done with RDF: `"accession": "https://raw.githubusercontent.com/HUPO-PSI/mzqc/master/cv/v0_0_11/qc-cv.obo#92"`.  This is my preferred solution, as it enables robust querying by a consumer of the format.

**Comment by Ozzard** [comment]
Option 4:

* Abandon JSON and move to a well-specified interchange format that has namespaces built in, such as XML. Querying tooling understands these mechanisms. Under no circumstances mix representations, for example part JSON and part XML; this makes automated querying essentially impossible.

**Comment by Ozzard** [comment]
I've uploaded three example files in [issue_99_examples.zip](https://github.com/HUPO-PSI/mzQC/files/4514889/issue_99_examples.zip). They're zipped because Github won't take files with either .mzqc or .json suffixes.

problem_ns12.mzqc and problem_ns21.mzqc show the issue. They're the same data with namespaces (ns1 and ns2) generated in arbitrary order, and wouldn't be crazy outputs from a mzQC writing package that rendered a model that was generated in memory.

unambiguous.mzqc shows the result of my preferred option, encoding the accession as a URI.  It looks horribly verbose, but quite a bit of that goes away if the duplication in accession and cvRef is removed per #100.

**Comment by mwalzer** [comment]
So if I understand correctly, the global scope would be:
1. choose a 'metric' from an ontology :arrow_right: get the accession
2. query some mzQC files for the values of given accession :arrow_right: get the value.
3. proceed however

Would this still be an issue for writing a generic query, if you can just regard the accession from the pick in the ontology as is, meaning ignoring the fact that the might all have a common prefix??

Because the entries in the mzQC _must_ have the **complete** accession string on record as it appears in a term entry in the ontology after `id:`. So if the term entry looks like 
```
[Term]
id: MS:1001193
name: confidence score
def: "Result of quality estimation: confidence score." [PSI:PI]
xref: value-type:xsd\:double "The allowed value-type for this CV term."
is_a: MS:1001092 ! peptide sequence-level identification statistic
is_a: MS:1001116 ! single protein identification statistic
```
then a mzQC entry should be like
```
{"cvRef": "psi-ms-v0", "accession": "MS:1001193", "name": "confidence score", "value": 42}
```
Or did I misunderstand how you want to approach writing generic queries?

**Comment by Ozzard** [comment]
Thanks, Mathias.  I reckon there's still a problem given that (per your comment to #100) multiple ontologies are allowed to use the same ID to refer to different terms.  A robust query must take this into account or risk returning incorrect answers in future; certainly I would expect the issue to come up if mzQC was ever used as an interchange format in a validated system.  So a query system still needs some way to determine the source of the particular accession - and ideally to do that in a reasonably performant way.

Paul Brack and I haven't been able to come up with a performant way of doing this in MS SQL Server (you end up having to pre-query to extract the namespace mapping for each mzQC file into a table, then run a custom query on each mzQC you have in the database, which doesn't scale to tens of thousands of QC files), or any way at all using JSONPath (https://goessner.net/articles/JsonPath/).

Is this a valid use case of mzQC at all, or should I be thinking differently about the problem and treating mzQC purely as an interchange format that requires custom import code for any use case other than interchange?

**Comment by bittremieux** [comment]
Sorry for the slow reply.

I think storing and querying mzQC files is an essential use case we definitely should support, so this is an important discussion.

I'm not sure the current format doesn't support that though. To robustly query you should specify the CV version to be sure that the term you're interested in actually has the specific accession you're querying on. So the query would be constructed to match the CV you need in the `cv` section and then use the corresponding `cvRef` and accession to match the quality metrics you want.
Basically it comes down to sort of a "join" between the CVs and the quality parameters based on the cvRef.

I'm definitely not in favor of option 2 to standardize mapping of prefixes to CVs. That's going to add significant overhead for us to maintain a mapping for all possible CVs people want to use and all possible versions thereof, and also less flexibility for mzQC producers.

I'm also not really a big fan of option 3 to include full URLs because it's overly verbose. Verbosity is a concern some people have already expressed with the current format.

Option 4 is definitely out imo because we explicitly switched from XML to JSON, in contrast to earlier PSI standards, because we needed the additional flexibility JSON affords us to store some types of metrics. And JSON is much nicer as an interchange format, etc.

**Comment by Ozzard** [comment]
Thanks, @bittremieux.  I agree with all of that in principle; the practical snag is 

> Basically it comes down to sort of a "join" between the CVs and the quality parameters based on the cvRef.

The devil is in the detail there.  @mwalzer, Paul Brack, and I have all independently had a go at doing this using the only standard JSON querying tool available (JsonPath) and have failed to come up with a workable single query.  All of us can come up with a two-step query that retrieves the cvRef for the CV then, as a separate step, uses that to retrieve the data.  Those two steps have to be performed independently for each mzQC file you have; there's some chance of optimising this if you have (say) a relational database, cache the mappings, and do the second query over groups of mzQC files that have the same mapping.  But it's a lot of hard work, and it doesn't scale.

I do think the WG should aim for a format where a single metric can be retrieved across multiple files, potentially generated by different tools, using a single JsonPath query and without escaping into the particular JsonPath implementation's underlying implementation language (easy in Javascript implementations, impossible in RDBMS implementations).  I think it's too much to expect that the query doesn't use JsonPath filters, despite the poor implementation of those in many DBMSs at present; that would limit the format so much that it would be unworkable.

Does this provide some kind of reasonable success criterion?

**Comment by mwalzer** [comment]
Yes, I think we should aim to include that in our use-case list. I suspect that we would be closest with option 3 and I have been toying with the concept since. @bittremieux I do agree with your opinions on the rest of the options, but we might be reasonably close if we allow, at least partially, some verbosity in favour of explicit term addressing. Common compression will deal with that nicely. And might be advisable regardless, real-world mzqc files tend to be lengthy. No big overhead for reading/writing mzqc.gz (at least for python). 

What I was thinking about:
1. recommend `cvTerm` use as-is with recording the ontology (+url) and version used, a mapping (via cvRef) and the usual accessions for terms used.
2. allow replacing `accession` in terms used with a direct PURL (e.g. http://purl.obolibrary.org/obo/MS_1000584) and a fixed marker in `cvRef` to indicate PURLs - this would render the controlledVocabularies section redundant but I think it would be good to keep as independent record
3. one usually would not expect files like in 2. unless in said use case. Luckily the 'conversion' should be easy and straight forward.

Things we would have to figure out:
PURLs - where does the version of a cv come into play and could we have PURLs with raw.github.com? @Ozzard can you help with that?
SPEC - the use case and the solution are not overly complicated but we'd need to write some easy to understand specification to avoid confusion.

**Comment by Ozzard** [comment]
I'd be rather worried if a new version of a vocabulary changed the meaning of an existing term (/accession).  If one needs a term with a different definition, then my strong recommendation would be to create the new term and deprecate use of the old term.  This is also why I don't recommend that term/accession IDs have any meaning, for example different numeric ranges being used for different kinds of thing.

As for PURLs, I reckon the WG should reserve an appropriate namespace there.  I *think* it's possible to link from obolibrary.org to a file hosted anywhere, as happens with the Unit Ontology.

**Comment by bittremieux** [comment]
I agree that this is an important issue, we should definitely support efficient querying of metrics across multiple files. This is a key use case.
I'm not entirely sold on any of the solutions yet because it feels less elegant than the way we're doing it now. But I can't come up with a better solution either, so option 3 might indeed be the way to go.

We should put this high on the list of things to discuss during the call next week. @Ozzard it would be great if you'd be able to join as well. The call will be on Wednesday at 14:00 GMT.

**Comment by Ozzard** [comment]
Thanks - I'll get call details from @mwalzer.

I also don't like any of these options, though the "usual" URLs in option 3 should be relatively tidy assuming the WG uses obofoundry or some similar URL space.

**Comment by bittremieux** [comment]
Yes, in that case we should at least try to (semi) standardize CV URLs, rather than including an entire hash in a Github URL to point to a specific version of a CV.

**Comment by bittremieux** [comment]
`cvTerm` was removed, instead terms are specified by their accession. Note that for this to work certain CV codes are reserved: `QC` for the QC CV, `MS` for the MS CV, `UO` for the unit ontology. Custom CVs MUST NOT cause namespaces clashes.
